import {defineConfig, devices} from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  // Visual baselines are reviewed against a pinned Chromium/Darwin renderer.
  // Keep that filename stable when the comparison runs in CI; snapshots are
  // never regenerated by the test job.
  snapshotPathTemplate: '{testDir}/{testFilePath}-snapshots/{arg}-chromium-darwin{ext}',
  timeout: 60_000,
  retries: 1,
  // The local demo API intentionally represents a shared appraisal workspace.
  // A single worker keeps browser coverage deterministic instead of allowing
  // concurrent suites to contend for seed data and rendering resources.
  workers: process.env.PLAYWRIGHT_WORKERS ? Number(process.env.PLAYWRIGHT_WORKERS) : 1,
  use: {
    baseURL: process.env.E2E_BASE_URL || 'http://localhost:5174',
    headless: true,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  expect: {
    timeout: 15_000,
    toHaveScreenshot: {
      animations: 'disabled',
      caret: 'hide',
      scale: 'css',
      maxDiffPixelRatio: 0.005,
    },
  },
  projects: [
    {name: 'chromium', use: {...devices['Desktop Chrome']}},
    {name: 'firefox', use: {...devices['Desktop Firefox']}},
    {name: 'webkit', use: {...devices['Desktop Safari']}},
  ],
  reporter: [['list']],
});
