apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: production-priority
value: 100
globalDefault: false
description: "This is the priority class for production pods - current users. Our top priority."
