apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: sandbox-priority
value: 6000
globalDefault: false
description: "This priority class is for our sandbox, where beta users can have fun"
