apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: swiftly-training
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: eb-appraisal-sha256
            image: gcr.io/appraisalai/swiftly:__REVISION_ID__-trainingserver
            command: ["/usr/local/bin/appraisal_train_extractor", "production_readonly.ini"]
            resources:
              requests:
                cpu: 4
                memory: 5Gi
              limits:
                cpu: 7
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
      backoffLimit: 4



