steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image for Vector Server
  args: ["build", "-t", "gcr.io/swiftly-2020/swiftly:$REVISION_ID-vectorserver", ".", "-f", "deployment/vector_server/Dockerfile"]
  timeout: 7200s
- name: 'gcr.io/cloud-builders/docker'
  id: Push Docker Image for Vector Server
  args: ["push", "gcr.io/swiftly-2020/swiftly:$REVISION_ID-vectorserver"]
  timeout: 3600s
- name: 'gcr.io/cloud-builders/kubectl'
  id: Fetch Kubernetes Auth
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Vector Server Deployment
  entrypoint: /bin/bash
  args:
  - "./deployment/vector_server/update_vector_server.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 15000s

