apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: swiftly-vectorserver
  name: swiftly-vectorserver-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: swiftly-vectorserver
  targetCPUUtilizationPercentage: 80

