apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: swiftly-vectorserver
  name: swiftly-vectorserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: swiftly-vectorserver
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: swiftly-vectorserver
    spec:
      containers:
      - image: gcr.io/appraisalai/swiftly:__REVISION_ID__-vectorserver
        imagePullPolicy: IfNotPresent
        name: eb-appraisal-sha256
        resources:
          requests:
            cpu: 500m
            memory: 9Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
