apiVersion: v1
kind: Service
metadata:
  name: swiftly-vectorserver
  labels:
    app: swiftly-vectorserver
  name: swiftly-vectorserver
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: swiftly-vectorserver
  sessionAffinity: None
  type: ClusterIP
