steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api", ".", "--build-arg", "SWIFTLY_ENV=$_SWIFTLY_ENV", "-f", "deployment/api_server/Dockerfile"]
  timeout: 7200s
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api"]
  timeout: 3600s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'swiftly-$_SWIFTLY_ENV-api'
  - 'eb-appraisal-sha256=gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  timeout: 600s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Demo Job
  entrypoint: /bin/bash
  args:
  - "./deployment/api_server/run_migration_job.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  - 'SWIFTLY_ENV=$_SWIFTLY_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Demo Job
  entrypoint: /bin/bash
  args:
  - "./deployment/api_server/update_demo_reset.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  - 'SWIFTLY_ENV=$_SWIFTLY_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 15000s


