steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api", ".", "--build-arg", "SWIFTLY_ENV=$_SWIFTLY_ENV", "-f", "deployment/api_server/Dockerfile"]
  timeout: 7200s
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api"]
  timeout: 3600s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'swiftly-$_SWIFTLY_ENV-api'
  - 'eb-appraisal-sha256=gcr.io/appraisalai/swiftly:$REVISION_ID-$_SWIFTLY_ENV-api'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  timeout: 600s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Run Migrations
  entrypoint: /bin/sh
  args:
  - '-c'
  - sed "s/REVISION_ID/$REVISION_ID/g;s/SWIFTLY_ENV/$_SWIFTLY_ENV/g" deployment/api_server/migration_job.yaml > migration_job_$_SWIFTLY_ENV.yaml
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'create'
  - '-f'
  - 'migration_job_$_SWIFTLY_ENV.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  timeout: 600s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Demo Job
  entrypoint: /bin/sh
  args:
  - '-c'
  - if test $SWIFTLY_ENV -eq testing then sed "s/REVISION_ID/$REVISION_ID/g;s/SWIFTLY_ENV/$_SWIFTLY_ENV/g" deployment/api_server/demo_reset_job.yaml > demo_reset_job_$_SWIFTLY_ENV.yaml && \
    kubectl apply -f demo_reset_job_$_SWIFTLY_ENV.yaml fi
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  - 'SWIFTLY_ENV=$_SWIFTLY_ENV'
timeout: 15000s


