apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: swiftly-demo-reset-SWIFTLY_ENV
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: eb-appraisal-sha256
            image: gcr.io/appraisalai/swiftly:REVISION_ID-SWIFTLY_ENV-api
            command: ["appraisal_load_sample_data",  "SWIFTLY_ENV.ini", "google-oauth2|117335766228984134502"]
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
          restartPolicy: OnFailure
      backoffLimit: 4



