apiVersion: batch/v1
kind: Job
metadata:
  name: swiftly-migration-demo
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: eb-appraisal-sha256
        image: gcr.io/appraisalai/swiftly:latest-demo-api
        command: ["appraisal_run_migrations",  "demo.ini"]
        resources:
          requests:
            cpu: 1
            memory: 512Mi
      restartPolicy: Never
  backoffLimit: 4

