apiVersion: batch/v1
kind: Job
metadata:
  name: swiftly-migration-testing
spec:
  template:
    spec:
      containers:
      - name: eb-appraisal-sha256
        image: gcr.io/appraisalai/swiftly:latest-testing-frontend
        command: ["appraisal_run_migrations",  "testing.ini"]
        resources:
          requests:
            cpu: 1
            memory: 512Mi
      restartPolicy: Never
  backoffLimit: 4
