apiVersion: batch/v1
kind: Job
metadata:
  name: swiftly-migration-SWIFTLY_ENV
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: eb-appraisal-sha256
        image: gcr.io/appraisalai/swiftly:REVISION_ID-SWIFTLY_ENV-api
        command: ["appraisal_run_migrations",  "SWIFTLY_ENV.ini"]
        resources:
          requests:
            cpu: 1
            memory: 512Mi
      restartPolicy: Never
  backoffLimit: 4
