steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Frontend Docker Image
  args:
    - "--destination=gcr.io/swiftly-2020/swiftly:$REVISION_ID-$_SWIFTLY_ENV-frontend"
    - "--cache=false"
    - "--cache-ttl=72h"
    - "--snapshotMode=time"
    - "build"
    - "."
    - "--build-arg"
    - "SWIFTLY_ENV=$_SWIFTLY_ENV"
    - "-f"
    - "deployment/frontend_server/Dockerfile"
  timeout: 1800s
- name: 'gcr.io/cloud-builders/docker'
  id: Push the API Server
  args:
    - "push"
    - "gcr.io/swiftly-2020/swiftly:$REVISION_ID-$_SWIFTLY_ENV-frontend"
  timeout: 1800s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Frontend Server Deployment
  entrypoint: /bin/bash
  args:
  - "./deployment/frontend_server/update_frontend_server.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  - 'SWIFTLY_ENV=$_SWIFTLY_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 3600s
