apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: swiftly-SWIFTLY_ENV-frontend
  name: swiftly-SWIFTLY_ENV-frontend-hpa
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/swiftly-SWIFTLY_ENV-frontend-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: swiftly-SWIFTLY_ENV-frontend
  targetCPUUtilizationPercentage: 80

